# Generated by Django 6.0.7 on 2026-07-22 06:10

import validation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/defaults/default.jpg', null=True, upload_to='users/%Y/%m/%d/', validators=[validation.validators.validate_file_extension, validation.validators.validate_image_size], verbose_name='Profile Image'),
        ),
    ]
